Add showSaveVideoAs  options
sindresorhus/electron-context-menu pull request #161
Opened 2022-08-11 03:16 UTC by and80506

add showSaveVideo、 showSaveVideoAs and showCopyVideoAddress options.
![image](https://user-images.githubusercontent.com/1769410/184058794-4f05d3d2-9fab-415c-8ad1-3ab2ee0657ba.png)

2022-08-11 23:04 UTC, sindresorhus requested changes

2022-08-11 23:04 UTC, sindresorhus commented on index.d.ts
> +		Show the `Save Video` menu item when right-clicking on an video.
```suggestion
		Show the `Save Video` menu item when right-clicking on a video.
```

2022-08-11 23:04 UTC, sindresorhus commented
Can you make the fixture video smaller by shortening the duration and maybe making it smaller in dimension? I don't want to waste 1 MB in this repo just on a fixture.

2022-08-11 23:04 UTC, sindresorhus commented
Can you fix the merge conflict?

2022-08-15 06:57 UTC, and80506 commented
> Can you make the fixture video smaller by shortening the duration and maybe making it smaller in dimension? I don't want to waste 1 MB in this repo just on a fixture.

OK

2022-08-19 14:55 UTC, merged